### ISSUE TITLE
Multiple Preferred Modes

### ISSUE THREAD

**Issue by justinlovinger** [alex-courtis/way-displays#113]
One monitor on my desktop, `DP-2` below, is initially set to the wrong mode. Note, `way-displays` gets the right "preferred" mode in the list of modes, but it gets the wrong "preferred" mode while setting it.

```
I [19:01:20] way-displays version 1.8.1
I [19:01:20] 
I [19:01:20] Found configuration file: /nix/store/91r9r2wsd6ms24dq5d1z9pl01afz18yy-way-displays-1.8.1/etc/way-displays/cfg.yaml
I [19:01:20] 
I [19:01:20] Active configuration:
I [19:01:20]   Arrange in a ROW aligned at the TOP
I [19:01:20]   Scaling: ON
I [19:01:20]   Auto scale: ON
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event6 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event13 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event5 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event10 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event11 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event12 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event7 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event8 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event9 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event18 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event19 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event20 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event1 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event2 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event3 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event4 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event0 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event14 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event15 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event16 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event17 failed: 13 Permission denied
W [19:01:20] 
W [19:01:20] WARNING: libinput open /dev/input/event21 failed: 13 Permission denied
I [19:01:20] 
I [19:01:20] HDMI-A-3 Arrived:
I [19:01:20]   info:
I [19:01:20]     name:     'HDMI-A-3'
I [19:01:20]     make:     'Ancor Communications Inc'
I [19:01:20]     model:    'ASUS VN248'
I [19:01:20]     serial:   'DCLMTF089140'
I [19:01:20]     desc:     'Ancor Communications Inc ASUS VN248 DCLMTF089140 (HDMI-A-3)'
I [19:01:20]     width:    530mm
I [19:01:20]     height:   300mm
I [19:01:20]     dpi:      91.73 @ 1920x1080
I [19:01:20]     mode:     1920 x 1080 @  60 Hz   60,000 mHz (preferred)  60,000 mHz  59,940 mHz
I [19:01:20]     mode:     1920 x 1080 @  50 Hz   50,000 mHz
I [19:01:20]     mode:     1920 x 1080 @  30 Hz   30,000 mHz  29,970 mHz
I [19:01:20]     mode:     1680 x 1050 @  60 Hz   59,883 mHz
I [19:01:20]     mode:     1440 x  900 @  60 Hz   59,901 mHz
I [19:01:20]     mode:     1440 x  576 @  50 Hz   50,000 mHz  50,000 mHz
I [19:01:20]     mode:     1440 x  480 @  60 Hz   60,000 mHz  60,000 mHz  59,940 mHz  59,940 mHz
I [19:01:20]     mode:     1280 x 1024 @  75 Hz   75,025 mHz
I [19:01:20]     mode:     1280 x 1024 @  60 Hz   60,020 mHz
I [19:01:20]     mode:     1280 x  960 @  60 Hz   60,000 mHz
I [19:01:20]     mode:     1280 x  800 @  60 Hz   59,910 mHz
I [19:01:20]     mode:     1280 x  720 @  60 Hz   60,000 mHz  60,000 mHz  59,940 mHz
I [19:01:20]     mode:     1280 x  720 @  50 Hz   50,000 mHz  50,000 mHz
I [19:01:20]     mode:     1152 x  864 @  75 Hz   75,000 mHz
I [19:01:20]     mode:     1024 x  768 @  75 Hz   75,029 mHz
I [19:01:20]     mode:     1024 x  768 @  70 Hz   70,069 mHz
I [19:01:20]     mode:     1024 x  768 @  60 Hz   60,004 mHz
I [19:01:20]     mode:      832 x  624 @  75 Hz   74,551 mHz
I [19:01:20]     mode:      800 x  600 @  75 Hz   75,000 mHz
I [19:01:20]     mode:      800 x  600 @  72 Hz   72,188 mHz
I [19:01:20]     mode:      800 x  600 @  60 Hz   60,317 mHz
I [19:01:20]     mode:      800 x  600 @  56 Hz   56,250 mHz
I [19:01:20]     mode:      720 x  576 @  50 Hz   50,000 mHz  50,000 mHz  50,000 mHz
I [19:01:20]     mode:      720 x  480 @  60 Hz   60,000 mHz  60,000 mHz  59,940 mHz  59,940 mHz  59,940 mHz
I [19:01:20]     mode:      720 x  400 @  70 Hz   70,082 mHz
I [19:01:20]     mode:      640 x  480 @  75 Hz   75,000 mHz
I [19:01:20]     mode:      640 x  480 @  67 Hz   66,667 mHz
I [19:01:20]     mode:      640 x  480 @  60 Hz   60,000 mHz  59,940 mHz  59,940 mHz
I [19:01:20]   current:
I [19:01:20]     scale:    1.000 (0.955)
I [19:01:20]     position: 3840,0
I [19:01:20]     mode:     1920x1080@60Hz (60,000mHz) (preferred)
I [19:01:20]     VRR:      off
I [19:01:20] 
I [19:01:20] DP-2 Arrived:
I [19:01:20]   info:
I [19:01:20]     name:     'DP-2'
I [19:01:20]     make:     'Viewteck Co., Ltd.'
I [19:01:20]     model:    'SUW49DA'
I [19:01:20]     serial:   '0000000000000'
I [19:01:20]     desc:     'Viewteck Co., Ltd. SUW49DA 0000000000000 (DP-2)'
I [19:01:20]     width:    1200mm
I [19:01:20]     height:   340mm
I [19:01:20]     dpi:      107.97 @ 5120x1440
I [19:01:20]     mode:     5120 x 1440 @ 120 Hz  120,000 mHz
I [19:01:20]     mode:     5120 x 1440 @  60 Hz   60,000 mHz (preferred)
I [19:01:20]     mode:     3840 x 2160 @  60 Hz   60,000 mHz  60,000 mHz  59,940 mHz
I [19:01:20]     mode:     3840 x 2160 @  50 Hz   50,000 mHz
I [19:01:20]     mode:     3840 x 2160 @  30 Hz   30,000 mHz  29,970 mHz
I [19:01:20]     mode:     3840 x 2160 @  25 Hz   25,000 mHz
I [19:01:20]     mode:     3840 x 2160 @  24 Hz   24,000 mHz  23,976 mHz
I [19:01:20]     mode:     2560 x 1600 @  85 Hz   84,951 mHz
I [19:01:20]     mode:     2560 x 1600 @  75 Hz   74,972 mHz
I [19:01:20]     mode:     2560 x 1600 @  60 Hz   59,987 mHz
I [19:01:20]     mode:     2560 x 1440 @ 120 Hz  120,000 mHz
I [19:01:20]     mode:     2560 x 1440 @  60 Hz   60,000 mHz
I [19:01:20]     mode:     2048 x 1152 @  60 Hz   60,000 mHz
I [19:01:20]     mode:     1920 x 1440 @  75 Hz   75,000 mHz
I [19:01:20]     mode:     1920 x 1440 @  60 Hz   60,000 mHz
I [19:01:20]     mode:     1920 x 1200 @  85 Hz   84,932 mHz
I [19:01:20]     mode:     1920 x 1200 @  75 Hz   74,930 mHz
I [19:01:20]     mode:     1920 x 1200 @  60 Hz   59,885 mHz
I [19:01:20]     mode:     1920 x 1080 @ 120 Hz  120,000 mHz 119,880 mHz
I [19:01:20]     mode:     1920 x 1080 @  60 Hz   60,000 mHz  60,000 mHz  59,940 mHz
I [19:01:20]     mode:     1920 x 1080 @  50 Hz   50,000 mHz
I [19:01:20]     mode:     1920 x 1080 @  30 Hz   30,000 mHz  29,970 mHz
I [19:01:20]     mode:     1920 x 1080 @  24 Hz   24,000 mHz  23,976 mHz
I [19:01:20]     mode:     1856 x 1392 @  75 Hz   75,000 mHz
I [19:01:20]     mode:     1856 x 1392 @  60 Hz   59,995 mHz
I [19:01:20]     mode:     1792 x 1344 @  75 Hz   74,997 mHz
I [19:01:20]     mode:     1792 x 1344 @  60 Hz   60,000 mHz
I [19:01:20]     mode:     1680 x 1050 @  85 Hz   84,941 mHz
I [19:01:20]     mode:     1680 x 1050 @  75 Hz   74,892 mHz
I [19:01:20]     mode:     1680 x 1050 @   0 Hz    0,000 mHz
I [19:01:20]     mode:     1600 x 1200 @  85 Hz   85,000 mHz
I [19:01:20]     mode:     1600 x 1200 @  75 Hz   75,000 mHz
I [19:01:20]     mode:     1600 x 1200 @  70 Hz   70,000 mHz
I [19:01:20]     mode:     1600 x 1200 @  65 Hz   65,000 mHz
I [19:01:20]     mode:     1600 x 1200 @  60 Hz   60,000 mHz
I [19:01:20]   current:
I [19:01:20]     (no mode)
I [19:01:20]     VRR:      off
I [19:01:20]     (disabled)
I [19:01:20] 
I [19:01:20] DP-2 Changing:
I [19:01:20]   from:
I [19:01:20]     (no mode)
I [19:01:20]     VRR:      off
I [19:01:20]     (disabled)
I [19:01:20]   to:
I [19:01:20]     mode:     3840x2160@60Hz (60,000mHz) (preferred)
I [19:01:20]     (enabled)
W [19:01:20] 
W [19:01:20] WARNING: Changes cancelled, retrying
```

**Comment by alex-courtis** [comment]
That's really interesting - preferred is definitely not correct. It looks like the native resolution of SUW49DA is indeed 5120 x 1440

Please post the output of `way-displays --yaml --get` so that I may more easily attempt to replicate/fix this.

Please attempt to set the mode to some native resolutions. It's not a proper fix, but it will at least determine whether we can set _a_ mode:

`way-displays --set MODE "SUW49DA" 5120 1440`

`way-displays --set MODE "SUW49DA" 5120 1440 60`

`way-displays --set MODE "SUW49DA" 5120 1440 120`

**Comment by alex-courtis** [comment]
FYI you can allow laptop lid detection and remove the error messages: https://github.com/alex-courtis/way-displays#laptop-lid-not-detected---permission-denied

**Comment by JustinLovinger** [comment]
Yes, I am manually setting the mode for now.

```
DONE: TRUE
CFG:
  ARRANGE: ROW
  ALIGN: TOP
  SCALING: TRUE
  AUTO_SCALE: TRUE
  MODE:
    - NAME_DESC: DP-2
      WIDTH: 5120
      HEIGHT: 1440
      HZ: 60
STATE:
  HEADS:
    - NAME: DP-2
      DESCRIPTION: Viewteck Co., Ltd. SUW49DA 0000000000000 (DP-2)
      MAKE: Viewteck Co., Ltd.
      MODEL: SUW49DA
      SERIAL_NUMBER: 0000000000000
      WIDTH_MM: 1200
      HEIGHT_MM: 340
      TRANSFORM: 0
      CURRENT:
        SCALE: 1.125
        ENABLED: TRUE
        X: 0
        Y: 0
      DESIRED:
        SCALE: 1.125
        ENABLED: TRUE
        X: 0
        Y: 0
      MODES:
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 60000
          PREFERRED: TRUE
          CURRENT: FALSE
        - WIDTH: 5120
          HEIGHT: 1440
          REFRESH_MHZ: 60000
          PREFERRED: TRUE
          CURRENT: TRUE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 30000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 29970
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 25000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 24000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 3840
          HEIGHT: 2160
          REFRESH_MHZ: 23976
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 5120
          HEIGHT: 1440
          REFRESH_MHZ: 120000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 2560
          HEIGHT: 1600
          REFRESH_MHZ: 84951
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 2560
          HEIGHT: 1600
          REFRESH_MHZ: 74972
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 2560
          HEIGHT: 1600
          REFRESH_MHZ: 59987
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 2560
          HEIGHT: 1440
          REFRESH_MHZ: 120000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 2560
          HEIGHT: 1440
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1440
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1440
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1856
          HEIGHT: 1392
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1856
          HEIGHT: 1392
          REFRESH_MHZ: 59995
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1792
          HEIGHT: 1344
          REFRESH_MHZ: 74997
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1792
          HEIGHT: 1344
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 2048
          HEIGHT: 1152
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1200
          REFRESH_MHZ: 84932
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1200
          REFRESH_MHZ: 74930
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1200
          REFRESH_MHZ: 59885
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 120000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 119880
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 30000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 29970
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 24000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 23976
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1600
          HEIGHT: 1200
          REFRESH_MHZ: 85000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1600
          HEIGHT: 1200
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1600
          HEIGHT: 1200
          REFRESH_MHZ: 70000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1600
          HEIGHT: 1200
          REFRESH_MHZ: 65000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1600
          HEIGHT: 1200
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1680
          HEIGHT: 1050
          REFRESH_MHZ: 84941
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1680
          HEIGHT: 1050
          REFRESH_MHZ: 74892
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1680
          HEIGHT: 1050
          REFRESH_MHZ: 59954
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1400
          HEIGHT: 1050
          REFRESH_MHZ: 84960
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1400
          HEIGHT: 1050
          REFRESH_MHZ: 74867
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1600
          HEIGHT: 900
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 1024
          REFRESH_MHZ: 85024
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 1024
          REFRESH_MHZ: 75025
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 1024
          REFRESH_MHZ: 60020
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 900
          REFRESH_MHZ: 84842
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 900
          REFRESH_MHZ: 59887
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 960
          REFRESH_MHZ: 85002
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 960
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 800
          REFRESH_MHZ: 84880
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1152
          HEIGHT: 864
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1024
          HEIGHT: 768
          REFRESH_MHZ: 75029
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1024
          HEIGHT: 768
          REFRESH_MHZ: 70069
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1024
          HEIGHT: 768
          REFRESH_MHZ: 60004
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 832
          HEIGHT: 624
          REFRESH_MHZ: 74551
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 72188
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 60317
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 56250
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 72809
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 66667
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 400
          REFRESH_MHZ: 70082
          PREFERRED: FALSE
          CURRENT: FALSE
    - NAME: HDMI-A-3
      DESCRIPTION: Ancor Communications Inc ASUS VN248 DCLMTF089140 (HDMI-A-3)
      MAKE: Ancor Communications Inc
      MODEL: ASUS VN248
      SERIAL_NUMBER: DCLMTF089140
      WIDTH_MM: 530
      HEIGHT_MM: 300
      TRANSFORM: 0
      CURRENT:
        SCALE: 1
        ENABLED: TRUE
        X: 4551
        Y: 0
      DESIRED:
        SCALE: 1
        ENABLED: TRUE
        X: 4551
        Y: 0
      MODES:
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 60000
          PREFERRED: TRUE
          CURRENT: TRUE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 30000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1920
          HEIGHT: 1080
          REFRESH_MHZ: 29970
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1680
          HEIGHT: 1050
          REFRESH_MHZ: 59883
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 1024
          REFRESH_MHZ: 75025
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 1024
          REFRESH_MHZ: 60020
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 900
          REFRESH_MHZ: 59901
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 960
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 800
          REFRESH_MHZ: 59910
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1152
          HEIGHT: 864
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1280
          HEIGHT: 720
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1024
          HEIGHT: 768
          REFRESH_MHZ: 75029
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1024
          HEIGHT: 768
          REFRESH_MHZ: 70069
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1024
          HEIGHT: 768
          REFRESH_MHZ: 60004
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 1440
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 832
          HEIGHT: 624
          REFRESH_MHZ: 74551
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 72188
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 60317
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 800
          HEIGHT: 600
          REFRESH_MHZ: 56250
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 576
          REFRESH_MHZ: 50000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 75000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 66667
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 60000
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 640
          HEIGHT: 480
          REFRESH_MHZ: 59940
          PREFERRED: FALSE
          CURRENT: FALSE
        - WIDTH: 720
          HEIGHT: 400
          REFRESH_MHZ: 70082
          PREFERRED: FALSE
          CURRENT: FALSE
RC: 0
```

Huh, the monitor in question appears to have *two* preferred modes. I am not sure why it even has 3840x2160 modes. The monitor does not have that many pixels... Could those modes be from a bug in `way-displays` or is this a bug in the monitor itself?

**Comment by alex-courtis** [comment]
> Huh, the monitor in question appears to have _two_ preferred modes. I am not sure why it even has 3840x2160 modes. The monitor does not have that many pixels... 

Many monitors lie about their modes or advertise fallback compatibility modes; I've seen this from some 2560x1440 montiors which advertise 4K.

> Could those modes be from a bug in `way-displays` or is this a bug in the monitor itself?

Good catch! It could be either. I'll dig.

```yaml
  MODE:
    - NAME_DESC: DP-2
      WIDTH: 5120
      HEIGHT: 1440
      HZ: 60
```

You might want to use `NAME_DESC: SUW49DA` as the port names like `DP-2` can change.
