### ISSUE TITLE
VRR not working as intended?

### ISSUE THREAD

**Issue by GrabbenD** [alex-courtis/way-displays#129]
# Issue
Every game has incredible stutter / output latency. It seems like the monitor isn't actually updating fast enough / vblank being incredibly slow. One example of this is Halo Infinite (XWayland) which is free to play on Steam

# Setup
- Distro: Arch Linux
- GPU: RX 6800 XT
- Monitor: AW3821DW
- Compositor: river-git
- Version: 1.8.2
- Config: default Way-Display config (`~/.config/way-displays/cfg.yaml`) apart from:
   ```
   MODE:
       # Resolution and refresh
       - NAME_DESC: DP-2
         WIDTH: 3840
         HEIGHT: 1600
         HZ: 119.982
   ```
