### ISSUE TITLE
Feature: Conditions

### ISSUE THREAD

**Issue by mrsobakin** [alex-courtis/way-displays#196]
Related: #169.

## Conditions

A feature that allows users to create highly flexible dynamic configurations, which can automatically determine and change the state of displays, without the need for the external programs or manual config reloads.

## Rationale

Conditions system would allow users to create portable and robust configurations, which do not to rely on workarounds and external scripts.

It may be used to define a variety of custom scenarios, starting from something simple like *"disable laptop display when the external display is plugged"*, going to *"change scale depending on connected displays"*, or even *"drop framerate when battery charge is below X%"*.

### Condition

At its core, each condition simply represents an expression that evaluates to be either `true` or `false`.

Proposed condition structure is as such:

```yaml
IF:
    # True if these displays are currently plugged
    PLUGGED: ["eDP-1", "DP-2"]

    # True if these displays are unplugged
    UNPLUGGED: ["HDMI-1"]

    # True if command finishes with status code=0 (parity with shell)
    # Command receives head name list (or ipc-like head list) as stdin.
    COMMAND: "some_command"
```

For condition to evaluate to true, all its subconditions must also be true.

### Usage

I propose to not create any additional root elements, and integrate the conditions system into the existing config keys.

For example, in the `DISABLED` key, conditions may look something like this:

```yaml
DISABLED:
    # Always disabled. Implicitly has `NULL` condition, and `NULL` condition is always true.
    - "HDMI-1"
    
    # Internal display is disabled if the external display is connected.
    - NAME_DESC: "eDP-1"
      IF:
          PLUGGED: ["DP-2"]

    # For demonstration purposes: let's say that it is also disabled when HDMI-3 is unplugged.
    - NAME_DESC: "eDP-1"
      IF:
          UNPLUGGED: ["HDMI-3"]
```

This would have a minor disadvantage of making configs slightly harder to parse, but it would greatly increase the readability for end users.

As one can see, for `eDP-1` to be disabled, only one of the conditions must be true. In other words, multiple conditions form a BOOLEAN OR.

This gives us an additional advantage: such lists of conditions form a [DNF](https://en.wikipedia.org/wiki/Disjunctive_normal_form) with respect to the display plugged-ness. This means that the user can describe ANY head configurations which should result in display being disabled, without having to rely on commands.

This, of course, extends beyond the ability to turn displays on and off. The conditions could also be implemented for modes:
```yaml
MODE:
    - NAME_DESC: HDMI-A-1
     HZ: 60
     IF:
         UNPLUGGED: ["eDP-1"]
```

**Comment by mrsobakin** [comment]
Due to the current implementation of `CHANGE_SUCCESS_CMD` spawning (specifically zombie reaping), making `COMMAND`  subcondition work proved to be... Well, I wouldn't say hard or impossible, but at least in the only fix I've come up with, it did require much more caution with syscalls. 

So, `COMMAND` is cool, but at least for now, it isn't planned.

**Comment by mrsobakin** [comment]
For now, my plan is as such:

1. Implement conditions with `PLUGGED` and `UNPLUGGED` subconditions.
2. Add conditional `DISABLED` support.

I think that it would cover most (if not all) real world use cases. Conditions in mode, scale, and etc. are a nice idea, but not a necessity.

**Comment by mrsobakin** [comment]
@alex-courtis I've opened a tracker issue instead of a draft PR to keep the discussion and development process separate. I would like you to review this idea and share your thoughts on the proposed config syntax and the conditions entities and their concept overall.

**Comment by alex-courtis** [comment]
> This would have a minor disadvantage of making configs slightly harder to parse, but it would greatly increase the readability for end users.

That's just fine. User experience comes first.

> I think that it would cover most (if not all) real world use cases. Conditions in mode, scale, and etc. are a nice idea, but not a necessity.

DISABLED is the most obvious and useful use case; it will be easy to add more on request.

> Due to the current implementation of `CHANGE_SUCCESS_CMD` spawning (specifically zombie reaping), making `COMMAND` subcondition work proved to be... Well, I wouldn't say hard or impossible, but at least in the only fix I've come up with, it did require much more caution with syscalls.
> 
> So, `COMMAND` is cool, but at least for now, it isn't planned.

Yes. Passing stdin/out and waiting for return codes isn't simple. I reckon it might be difficult to control execution and we might end up calling it a lot.

> This gives us an additional advantage: such lists of conditions form a [DNF](https://en.wikipedia.org/wiki/Disjunctive_normal_form) with respect to the display plugged-ness. This means that the user can describe ANY head configurations which should result in display being disabled, without having to rely on commands.

That works - it's an AND of major with restricted but useful ORs in the minor.

Thinking about multiple IF conditions - evaluate true if one of a set of conditions evaluates true e.g. disable when (HDMI-4 is plugged in) or (DP-1 is plugged in and HDMI-3 is not)
```yaml
DISABLED:
  - NAME_DESC: "eDP-1"
    IF:
      - UNPLUGGED: ["HDMI-3"]
        PLUGGED: ["DP-1"]
      - PLUGGED: ["HDMI-4"]
```
Not sure how useful that is; it would also add complexity to UX and code.
It could always be added later, as we could parse one or the other.
Never mind me....


This sounds great. Plan is good - start simple, release MVP and we can iterate as needed.

**Comment by mrsobakin** [comment]
> Thinking about multiple IF conditions - evaluate true if one of a set of conditions evaluates true e.g. disable when (HDMI-4 is plugged in) or (DP-1 is plugged in and HDMI-3 is not)
> 
> DISABLED:
>   - NAME_DESC: "eDP-1"
>     IF:
>       - UNPLUGGED: ["HDMI-3"]
>         PLUGGED: ["DP-1"]
>       - PLUGGED: ["HDMI-4"]

Love the idea. Doesn't seem that different from the current model -- condition structure stays the same, but `IF` is now a list of conditions instead of a single one. Would do wonders to reduce the repetition.

**Comment by alex-courtis** [comment]
> Love the idea. Doesn't seem that different from the current model -- condition structure stays the same, but `IF` is now a list of conditions instead of a single one. Would do wonders to reduce the repetition.

Only if you're happy. We should direct users to use the first form in the case of a simple OR, for simplicity i.e.
```yaml
DISABLED:
    # Always disabled. Implicitly has `NULL` condition, and `NULL` condition is always true.
    - "HDMI-1"
    
    # Internal display is disabled if the external display is connected.
    - NAME_DESC: "eDP-1"
      IF:
          - PLUGGED: ["DP-2", "HDMI-1"]
```

rather than

```yaml
DISABLED:
    # Always disabled. Implicitly has `NULL` condition, and `NULL` condition is always true.
    - "HDMI-1"
    
    # Internal display is disabled if the external display is connected.
    - NAME_DESC: "eDP-1"
      IF:
          - PLUGGED: ["DP-2"]
          - PLUGGED: [ "HDMI-1"]
```
