### ISSUE TITLE
Layout Changes Failed After Successful Modeset

### ISSUE THREAD

**Issue by alex-courtis** [alex-courtis/way-displays#38]
`G1LMQS094673` plugged into Dell 5xxx via "4K" HDMI cable. Start way-displays with sway or after. b2b31c5

G1LMQS094673 is functional, laptop display is not.

```yaml
MODE:
  - NAME_DESC: Ancor Communications Inc ROG PG27AQ G1LMQS094673
    WIDTH: 3840
    HEIGHT: 2160
LOG_THRESHOLD: DEBUG
```

[sway.1.acourtis.log](https://github.com/alex-courtis/way-displays/files/8460778/sway.1.acourtis.log)
[way-displays.1.acourtis.log](https://github.com/alex-courtis/way-displays/files/8460779/way-displays.1.acourtis.log)
