### ISSUE TITLE
Feature: AUTO_SCALE_ROUND

### ISSUE THREAD

**Issue by alex-courtis** [alex-courtis/way-displays#40]
Round calculated scale to the nearest integer.

**Comment by xeruf** [comment]
Very good idea, as I have observed whole numbers looking a lot clearer, so I would rather have 2 than 2.125!
Also, if the AUTO_SCALE option could be a number as a DPI factor, that would be awesome!

**Comment by alex-courtis** [comment]
> Also, if the AUTO_SCALE option could be a number as a DPI factor, that would be awesome!

Confirming: you'd like a number|boolean, with TRUE effectively the same as 96:
```yaml
AUTO_SCALE: TRUE
-- or default
AUTO_SCALE: 96
-- or 
AUTO_SCALE: 72
```
```
