### ISSUE TITLE
Feature: Arrange: row|column Align: bottom|middle|top|left|right

### ISSUE THREAD

**Issue by steveb-123** [alex-courtis/way-displays#8]
Thanks for the great package!

By default dissimilar-sized displays align by the top edge which is not easy to accomplish in the physical world with a laptop on a desk with an external display. Thus, the mouse, for example, does not 'flow' properly from one display to the next.

![smaller](https://user-images.githubusercontent.com/67741912/138739408-71a6c363-9855-483f-b801-c2d2dda1c88f.jpg)

It would be helpful if there were the ability to set the position alignment to 'Bottom', and have way-displays do the math to make it happen. I would propose that Bottom should be the default, also.

**Comment by alex-courtis** [comment]
That's fantastic, thank you!

I will include it in the README - finally a "screenshot".

**Comment by alex-courtis** [comment]
Added all arrange and align combinations.

```yaml
# Arrange displays in a ROW (default, left to right) or a COLUMN (top to bottom)
ARRANGE: ROW

# Align ROWs at the TOP (default), MIDDLE or BOTTOM
# Align COLUMNs at the LEFT (default), MIDDLE or RIGHT
ALIGN: TOP
```

Before updating the README etc. I would gratefully appreciate your testing as well as reviewing the language / names, @steveb-123 

Many thanks for all the direction and feedback so far; these additions should be useful to many.
