### ISSUE TITLE
AUTO_SCALE as a DPI factor

### ISSUE THREAD

**Issue by alex-courtis** [alex-courtis/way-displays#81]
https://github.com/alex-courtis/way-displays/issues/40#issuecomment-1486932209

AUTO_SCALE number|boolean number|boolean, with TRUE effectively the same as 96:
```yaml
-- default, 96
AUTO_SCALE: TRUE
-- explicit default
AUTO_SCALE: 96
-- or user
AUTO_SCALE: 72
```
