### ISSUE TITLE
"profiles"

### ISSUE THREAD

**Issue by edrex** [alex-courtis/way-displays#83]
As a floating laptop user, I would like to specify multiple display layout settings profiles which apply based on the currently connected outputs (and possibly other conditions like laptop lid switch state, explicit profile selection via IPC).

This isn't a great user story, but basically, I want

 - Maximum expressivity when specifying a new station layout, at which way-displays succeeds 100% via ARRANGE and ALIGN vs kanshi's pixel coordinate based layout specification.
 - Fewest instances of manual intervention required: I only want to have to mess with config when adding a new novel station that doesn't conform to my default layout. Here, way-displays doesn't have a sufficient mechanism yet. While the current mechanism allows for  some flexibility in output ORDER, it doesn't allow conditional application of other config keys (ARRANGE, ALIGN, etc) and so requires manual intervention when switching stations whenever these keys need to change.

IMO what is needed is a kanshi-style "profiles" mechanism where each profile has a set of matching rules and a config block to apply. The profiles could be mutually-exclusive (first match wins) or layered (which would allow flexibly specifying defaults). This way, all config keys are subject to matching, and new matching rules can be added to introduce new axes of conditionality.

## Workarounds

Currently, I have multiple commented blocks and whenever I switch stations, I open the config in my editor and switch the active one. It's not a huge deal, and I like it way better than the kanshi UX. This could also be done via the IPC mechanism, but that just kicks the ball down the road.

Anyway, I'm happy with things as they are now but I see the focus making ORDER super flexible as a distraction.

**Comment by alex-courtis** [comment]
> IMO what is needed is a kanshi-style "profiles" mechanism where each profile has a set of matching rules and a config block to apply.

I think that's the key part here. The story will be achieved by setting the explicit configuration per-profile. Falling back to a default will still be useful. The behaviour of new displays can be best effort configured by profile or default, adding a new profile if needed.

My workarounds:
* Originally I had separate config files per machine, configured via my dotfile manager
* Now I just set the order in such a specific way that it matches the 3 machines I use, which are all left-to-right
That's not sufficient.

**Comment by alex-courtis** [comment]
> Currently, I have multiple commented blocks and whenever I switch stations, I open the config in my editor and switch the active one.

Keep in mind the [CLI](https://github.com/alex-courtis/way-displays/blob/master/doc/CONFIGURATION.md#command-line). You can configure persistently or ephemerally.

You can also use the [IPC API](https://github.com/alex-courtis/way-displays/blob/master/doc/IPC.md) if you're sufficiently motivated.

See #65 which will add user hooks.

Regardless, profiles are a desirable solution.

**Comment by alex-courtis** [comment]
> IMO what is needed is a kanshi-style "profiles" mechanism where each profile has a set of matching rules and a config block to apply.

Can you please draft some rules that we may add to cfg.yaml? My imagination is poor and can't see much beyond hostname or display name.

**Comment by edrex** [comment]
> ... separate config files per machine, configured via my dotfile manager

I use YADM - its per-host files feature can do this. I plan to add a Nix Home-Manager module for way-displays, which can differentiate per-host. Still, one config across machines seems like a nice convenience.

> [CLI](https://github.com/alex-courtis/way-displays/blob/master/doc/CONFIGURATION.md#command-line) ... persistently or ephemerally.

Oh, a comp/shell keybind to toggle the arrange/align would be nicer than editing the config file. Thanks!

> I just set the order ... matches the 3 machines I use ... all left-to-right

I'd guess for a majority of users one arrange/align value will work across all their stations. I don't want to nudge you into adding features [YAGNI](https://martinfowler.com/bliki/Yagni.html)!

**Comment by edrex** [comment]
> Can you please draft some rules that we may add to cfg.yaml?

It seems like the only really necessary dynamic profile matching criteria is that a given set of outputs are present.

- Lid switch state already does what everyone wants it seems
- Host matching could be useful, but since it won't change dynamically, it could be switched as a preprocessing step by eg YADM or home-manager. Also support could be added in a follow-up.

I first thought overloading the `ORDER` field, so that all entries in the order field would have to have a match for the profile to be applied (similar to kanshi's approach).  I'm not sure how that would work with the new regex support though. Some rules may match multiple outputs?

Maybe there's still a way to make profile matching work via the `ORDER` field, but another possibility would be to add a dedicated field for profile matching:



```yaml
PROFILES:
  a-profile-with-no-match-rule-always-applies:
    ARRANGE: COL # by default, unknown displays go above the laptop screen, eg for projectors
    ALIGN: MIDDLE
    ORDER:
      - '!.*$'
      - 'eDP-1' # eDP-1 defaults to last
  horizontal-laptop-right:
    MATCH:
      - '!(^Sharp Corporation 0x148D$)|(^Dell)' # When either of these displays are present, apply this profile atop the previous one
    ARRANGE: ROW
    ALIGN: BOTTOM
  hackerspace:
    MATCH:
      - 'Sharp Corporation 0x148D'
      - 'Monitor Maker ABC123' # When both of these displays are present, apply this profile too
    ORDER:
      - 'eDP-1' # in the hackerspace, laptop is on left
      - '!^Sharp'
      - '!^Monitor Maker'
```

WDYT?

`MATCH` could be named something else like `DISPLAYS`. If we ever wanted to additionally match on eg host, a `HOST` field could be added.

@matthewwardrop also curious if you have feedback/ideas here.

**Comment by alex-courtis** [comment]
```yaml
PROFILES:
  horizontal-laptop-right:
     MATCH:
```

That works. Keeping it simple, all params could go in each profile, overriding defaults. Merge methods are already present.
`LAPTOP_DISPLAY_PREFIX` would be annoying to build but possible.
`LOG_THRESHOLD` doesn't make much sense and would likely result in strange output.

Bonus points for Martin Fowler reference.

```yaml
PROFILES:
  a-profile-with-no-match-rule-always-applies:
```

We could just use the toplevel defaults

**Comment by alex-courtis** [comment]
There will be a nice solution for `MATCH`, but I cannot imagine it.

Even if we don't implement host matching, we should leave the door open for it and other future matches.

@matthewwardrop ideas please!

**Comment by alex-courtis** [comment]
> Some rules may match multiple outputs?

I think we can trust the user. If they get a match for each of the displays, the profile applies.

It would be documented.

**Comment by matthewwardrop** [comment]
Hi! Sorry for the delay, with things busy at work and with four munchkins at home, I don't have as much time as I'd like to clear out my inbox.

I also like the idea of context specific overrides... But like @edrex I use YADM as a workaround for this on my machine. If support were added, I'd keep the config as is, and then have context overlays that are matched in... Something like:

```
# usual config
ARRANGE: ...
ALIGN: ...
ORDER: ...

OVERLAYS:
    WORK: # name
        # nested config, dedented and processed like normal config, and then merged into parent config if MATCH is satisfied
        MATCH:
            OUTPUTS: # nested just in case we want to support matches on other things
                - usual regex or strings
        ALIGN: ....
        ....
```
